### ISSUE TITLE
gen/golang: error on json unmarshalling

### ISSUE THREAD

**Issue by dude333** [webrpc/webrpc#50] opened 2019-06-08 17:08 UTC
I got this error on my program when using a struct as function parameter and then I saw the same situation in the _golang-basics example_.

You can reproduce the error by running the example:

    cd _examples/golang-basics
    go run .

And when you try to find a user, it issues a fatal error:

    curl -v -X POST -H"Content-Type: application/json" -v -d '{"q":"123"}' http://localhost:4244/rpc/ExampleService/FindUser

I figured out that the error is in the `serveFindUserJSON` function on the generated Go file `example.gen.go`:

    // line 350
    reqContent := struct {
      Arg0 *SearchFilter `json:"s"`
    }{}
   
    // line 362
    err = json.Unmarshal(reqBody, &reqContent)

It's trying to unmarshall Arg0 from the received json, that's why it's crashing.

To fix it I just added .Arg0 to reqContent:

    err = json.Unmarshal(reqBody, &reqContent.Arg0)

(The crash itself is not caused by this error, it's due to the lack of proper checking on the received parameters at the FindUser function.)

**Comment by pkieltyka** [comment] 2019-06-08 20:45
@dude333 thanks for the report, I'll make sure to add a clean error for encoding/decoding errors like above.

the reason this happens in golang-basics is that the rpc method `FindUser` is defined as `FindUser(s: SearchFilter) => (name: string, user: User)` in ridl, which means its expecting `"s"` to be passed as well for the argument name which contains the `SearchFilter` object

like so..

```
curl -v -X POST -H"Content-Type: application/json" -v -d '{"s": { "q":"123" }}' http://localhost:4242/rpc/ExampleService/FindUser
```

**Comment by pkieltyka** [comment] 2019-06-08 20:49
the Go, JS and TS clients will use the correct argument names automatically btw, is there a reason you're querying it by hand or did you come across this error some other way?

**Comment by pkieltyka** [comment] 2019-06-08 20:58
I reviewed the server error checking code, and it does the right thing to recover from the panic when passed invalid call data. The marshaller perhaps could have given a better warning though. Closing this as its not a bug.

**Closed by pkieltyka** 2019-06-08 20:58 UTC

**Comment by dude333** [comment] 2019-06-12 03:15
@pkieltyka, the problem was actually in my parameter passed, in the client side, to my js api function call. Instead of `api.fn({ objParm })` I was using `api.fn(objParm)`.

Thanks for the catch, and for contributing to this amazing tool.
