### ISSUE TITLE
Property 'cause' in type 'WebrpcError' is not assignable to the same property in base type 'Error'.  

### ISSUE THREAD

**Issue by robfordww** [webrpc/webrpc#231] opened 2023-09-04 12:50 UTC
Hi,

Possible bugreport regarding the typescript generated file.

I get the typescript error below from the *.gen-ts file. Probably some nitpicking from the typescript system as everything seems to run fine.

As far as I know, I run the latest versions

> webrpc-gen --version
> webrpc-gen v0.13.0

```
Property 'cause' in type 'WebrpcError' is not assignable to the same property in base type 'Error'.
  Type 'string | undefined' is not assignable to type 'Error | undefined'.
```

![image](https://github.com/webrpc/webrpc/assets/24738409/96d4068e-27d4-4d21-8107-90612625fd39)

**Comment by kolberg-dev** [comment] 2023-09-27 18:12
Hey,

In Typescript 4.6 there was an issue with the type for the 'cause', allowing the cause to only be of type Error. 
Fixed in https://github.com/microsoft/TypeScript/pull/49639. 

If you upgrade Typescript (or change the build target to before es2022) the error should be resolved

**Comment by VojtechVitek** [comment] 2023-09-27 18:15
Thanks for explaining @kolberg-dev :)

**Closed by VojtechVitek** 2023-09-27 18:15 UTC
