### ISSUE TITLE
Add support for map<enum_type, some_other_type>

### ISSUE THREAD

**Issue by c2h5oh** [webrpc/webrpc#44] opened 2019-04-29 14:59 UTC
Right now only basic types are supported

**Comment by pkieltyka** [comment] 2019-04-29 23:41
@c2h5oh perhaps the issue is using enum_type as the key. webrpc might right now require string or number as the key, but any value is supported already as you can see in https://github.com/webrpc/webrpc/blob/master/_examples/golang-basics/example.ridl#L46

for enum_type, since its number based, should be pretty easy to add support for it eventually

**Comment by c2h5oh** [comment] 2019-05-13 18:08
That's exactly what this ticket is about - being able to end up with `map[enumType]valueType` on go side

**Comment by pkieltyka** [comment] 2019-09-16 14:44
@xiam this would be really nice to add support for too, and should be easy to support in parser since enum's are all numbers under the hood

**Comment by pkieltyka** [comment] 2024-02-23 11:29
btw, im pretty sure once https://github.com/webrpc/webrpc/issues/55 is solved, then this ticket will be closed along with it

**Comment by VojtechVitek** [comment] 2024-06-18 07:52
Fixed in https://github.com/webrpc/webrpc/pull/294 🎉

**Closed by VojtechVitek** 2024-06-18 07:52 UTC
Labels: todo
